CREATE TABLE ARTICLE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	YEAR INTEGER NOT NULL,
	MONTH INTEGER NOT NULL,
	MOVIE_TYPE VARCHAR(1) NOT NULL,
	POINT INTEGER NOT NULL,
	TEXT VARCHAR(5000),
	CREATED_TIME TIMESTAMP,
	MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO ARTICLE	VALUES(1, '劇場版　ガールズ＆パンツァー', 2015, 11, 'D', 98, 'ガルパンはいいぞ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ARTICLE	VALUES(2, 'ハル', 2013, 6, 'D', 95, '無名の名作', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
