CREATE TABLE ARTICLE (
	ID INTEGER PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	YEAR INTEGER NOT NULL,
	MONTH INTEGER NOT NULL,
	MOVIE_TYPE VARCHAR(1) NOT NULL,
	TEXT VARCHAR(5000),
	CREATE_TIME TIMESTAMP
);

INSERT INTO ARTICLE	VALUES(1, '劇場版　ガールズ＆パンツァー', 2015, 11, 'D', 'ガルパンはいいぞ', '2017-01-20 00:00:00');
