CREATE TABLE ARTICLE_CATEGORY (
	ARTICLE_ID INTEGER,
	CATEGORY VARCHAR(2)
);

INSERT INTO ARTICLE_CATEGORY VALUES(1, 'AN');
INSERT INTO ARTICLE_CATEGORY VALUES(1, 'AC');
INSERT INTO ARTICLE_CATEGORY VALUES(2, 'AN');
INSERT INTO ARTICLE_CATEGORY VALUES(2, 'DR');