CREATE TABLE ARTICLE_ARTICLE (
	ID INTEGER PRIMARY KEY,
	FROM_ID INTEGER,
	TO_ID INTEGER
);

CREATE SEQUENCE ARTICLE_ARTICLE_ID_SEQ
START WITH 1
INCREMENT BY 1
;

INSERT INTO ARTICLE_ARTICLE VALUES(1, 1, 2);